# -*- coding: utf-8 -*-
"""Lab 8 Pandas-III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G48y-PSFB33XqhLznSEh1do1QShsxT78
"""

# Commented out IPython magic to ensure Python compatibility.
#------------Different Ways of Creating DataFrame-------------
from google.colab import drive 
drive.mount('/content/drive')
# %pwd
# %cd /content
# %ls
# %cd drive/My Drive/Colab Notebooks
# %ls
import pandas as pd
df = pd.read_csv("weather_data.csv") 
df

df=pd.read_excel("weather_data.xlsx","Sheet1") 
df


weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
    }



df = pd.DataFrame(weather_data) 
df

weather_data = [ ('1/1/2017',32,6,'Rain'),
                ('1/2/2017',35,7,'Sunny'),
                ('1/3/2017',28,2,'Snow') ]
df = pd.DataFrame(data=weather_data,
columns=['day','temperature','windspeed','event'])
df

weather_data = [
                {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
                {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
                {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
                ]
df = pd.DataFrame(data=weather_data,
columns=['day','temperature','windspeed','event'])
df

#--------------Read Write Excel CSV File----------------------
import pandas as pd

df = pd.read_csv("stock_data.csv") 
df

df = pd.read_csv("stock_data.csv", skiprows=1) 
df

df = pd.read_csv("stock_data.csv", header=1) # skiprows and header are kind of same
df

df = pd.read_csv("stock_data.csv", header=None, names =
["ticker","eps","revenue","people"])
df

df = pd.read_csv("stock_data.csv", nrows=2)
df

df = pd.read_csv("stock_data.csv", na_values=["n.a.", "not available"]) 
df

df = pd.read_csv("stock_data.csv", na_values={ 'eps': ['not available'],
'revenue': [-1],
'people': ['not available','n.a.']
})
df


df.to_csv("new.csv", index=False) 
df.columns

df.to_csv("new.csv",header=False)
df.to_csv("new.csv", columns=["tickers","price"], index=False)

df = pd.read_excel("stock_data.xlsx","Sheet1") 
df

def convert_people_cell(cell): 
  if cell=="n.a.":
    return 'Sam Walton' 
  return cell

def convert_price_cell(cell): 
  if cell=="n.a.":
    return 50 
  return cell

df = pd.read_excel("stock_data.xlsx","Sheet1", converters= { 'people': convert_people_cell,
'price': convert_price_cell
})
df


df.to_excel("new.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)

df_stocks = pd.DataFrame({
'tickers': ['GOOGL', 'WMT', 'MSFT'], 'price': [845, 65, 64 ],
'pe': [30.37, 14.26, 30.97],
'eps': [27.82, 4.61, 2.12]
})

df_weather = pd.DataFrame({
'day': ['1/1/2017','1/2/2017','1/3/2017'],
'temperature': [32,35,28], 'event': ['Rain', 'Sunny', 'Snow']
})

with pd.ExcelWriter('stocks_weather.xlsx') as writer: 
  df_stocks.to_excel(writer, sheet_name="stocks") 
  df_weather.to_excel(writer, sheet_name="weather")

  #---------------------Handle Missing Data: fillna, dropna, interpolate---------------

# %cd /content/drive/My Drive/Colab Notebooks

import pandas as pd
df = pd.read_csv("weather_data_1.csv",parse_dates=['day']) 
type(df.day[0])
df

df.set_index('day',inplace=True) 
df

new_df = df.fillna(0) 
new_df

new_df = df.fillna({ 'temperature': 0, 'windspeed': 0, 'event': 'No Event' })

new_df

new_df = df.fillna(method="ffill") 
new_df

new_df = df.fillna(method="bfill") 
new_df

new_df = df.fillna(method="bfill", axis="columns") # axis is either "index" or "columns"
new_df

new_df = df.fillna(method="ffill",limit=1) 
new_df

new_df = df.interpolate() 
new_df

new_df = df.interpolate(method="time") 
new_df

new_df = df.dropna() 
new_df

new_df = df.dropna(how='all') 
new_df

new_df = df.dropna(thresh=1)
# any row/column with number of Non-NA value < thresh will be removed new_df

dt = pd.date_range("01-01-2017","01-11-2017") 
idx = pd.DatetimeIndex(dt)
df.reindex(idx)

#-------------------------Handle Missing Data: fillna, dropna, interpolate-------------
# %cd /content/drive/My Drive/Colab Notebooks

import pandas as pd 
import numpy as np 
df = pd.read_csv("weather_data_2.csv") 
df

new_df = df.replace(-99999, value=np.NaN) 
new_df

new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

new_df = df.replace({
'temperature': -99999,
'windspeed': -99999,
'event': '0'
}, np.nan)
new_df



new_df = df.replace({
    -99999: np.nan, 'no event': 'Sunny',


})
new_df






# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'',
                    regex=True)
new_df

df = pd.DataFrame({
'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

#--------------Group By (Split Apply Combine)------------------
# %cd /content/drive/My Drive/Colab Notebooks

import pandas as pd
df = pd.read_csv("weather_by_cities.csv") 
df
g = df.groupby("city") 
g

for city, data in g: 
  print("city:",city) 
  print("\n") 
  print("data:",data)

g.get_group('mumbai') 
g.max()
g.mean()

g.min() 
g.describe() 
g.size()

# %matplotlib inline 
g.plot()

def grouper(df, idx, col):
  if 80 <= df[col].loc[idx] <= 90:
    return '80-90'
  elif 50 <= df[col].loc[idx] <= 60:
    return '50-60' 
  else:
    return 'others'

g = df.groupby(lambda x: grouper(df, x, 'temperature')) 
g

for key, d in g:
  print("Group by Key: {}\n".format(key)) 
  print(d)

#----------------Concat Dataframes---------------------
import pandas as pd

india_weather = pd.DataFrame({
"city": ["mumbai","delhi","banglore"], "temperature": [32,45,30],
"humidity": [80, 60, 78]
})
india_weather

us_weather = pd.DataFrame({ "city": ["new york","chicago","orlando"], "temperature": [21,14,35], "humidity": [68, 65, 75] })
us_weather

df = pd.concat([india_weather, us_weather]) 
df

df = pd.concat([india_weather, us_weather], ignore_index=True)

df

df = pd.concat([india_weather, us_weather], keys=["india", "us"]) 
df
df.loc["us"]

df.loc["india"]

temperature_df = pd.DataFrame({ "city": ["mumbai","delhi","banglore"], "temperature": [32,45,30],
}, index=[0,1,2]) 
temperature_df

windspeed_df = pd.DataFrame({ "city": ["delhi","mumbai"], "windspeed": [7,12],
}, index=[1,0]) 
windspeed_df

df = pd.concat([temperature_df,windspeed_df],axis=1) 
df

s = pd.Series(["Humid","Dry","Rain"], name="event") 
s

df = pd.concat([temperature_df,s],axis=1) 
df

